export const GET_PACKAGE_SUGGESTION_REQ = "GET_PACKAGE_SUGGESTION_REQ";
export const GET_PACKAGE_SUGGESTION_SUC = "GET_PACKAGE_SUGGESTION_SUC";
export const GET_PACKAGE_SUGGESTION_FAIL = "GET_PACKAGE_SUGGESTION_FAIL";
