export {
    GET_PACKAGE_SUGGESTION_FAIL,
    GET_PACKAGE_SUGGESTION_REQ,
    GET_PACKAGE_SUGGESTION_SUC,

    GET_DEPENDENCY_REQ,
    GET_DEPENDENCY_SUC,
    GET_DEPENDENCY_FAIL,
    
    SET_PACKAGE_INFO,
    SET_USER_PACKAGE_TO_PROCESS,
    SET_PAGE,
} from "./landingPage";