export const GET_PACKAGE_SUGGESTION_REQ = "GET_PACKAGE_SUGGESTION_REQ";
export const GET_PACKAGE_SUGGESTION_SUC = "GET_PACKAGE_SUGGESTION_SUC";
export const GET_PACKAGE_SUGGESTION_FAIL = "GET_PACKAGE_SUGGESTION_FAIL";

export const SET_PACKAGE_INFO = "SET_PACKAGE_INFO";
export const SET_USER_PACKAGE_TO_PROCESS = "SET_USER_PACKAGE_TO_PROCESS";