/** Actions to retrieve list of packages based on user search */
export const GET_PACKAGE_SUGGESTION_REQ = "GET_PACKAGE_SUGGESTION_REQ";
export const GET_PACKAGE_SUGGESTION_SUC = "GET_PACKAGE_SUGGESTION_SUC";
export const GET_PACKAGE_SUGGESTION_FAIL = "GET_PACKAGE_SUGGESTION_FAIL";

export const GET_DEPENDENCY_REQ = "GET_DEPENDENCY_REQ";
export const GET_DEPENDENCY_SUC = "GET_DEPENDENCY_SUC";
export const GET_DEPENDENCY_FAIL = "GET_DEPENDENCY_FAIL";

export const SET_PACKAGE_INFO = "SET_PACKAGE_INFO";
export const SET_USER_PACKAGE_TO_PROCESS = "SET_USER_PACKAGE_TO_PROCESS";
export const SET_PAGE = "SET_PAGE";
